# ------------------------------------ #
#       Mad Chatter Configuration      #
# ------------------------------------ #

websocket_backend: MadChatter::Servers::EventMachineWebSocket
websocket_port: 8100
